workflows:
  ios-release-build:
    name: WidgetKit Demo IPA
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: codemagic

    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: pl.wojciechkulik.WidgetKit-Demo

    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles --project "WidgetKit Demo.xcodeproj"

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "WidgetKit Demo.xcodeproj" \
            --scheme "WidgetKit Demo"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
